spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1121
    url: jdbc:mysql://127.0.0.1:3306/test
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
